PLAYER_MAP = {
    "Adam": {"position": "cutter", "gender-match": "men"},
    "Andy": {"position": "cutter", "gender-match": "men"},
    "Audrey": {"position": "cutter", "gender-match": "women"},
    "Chloe": {"position": "cutter", "gender-match": "women"},
    "Christine": {"position": "handler", "gender-match": "women"},
    "Dan": {"position": "handler", "gender-match": "men"},
    "Devanee": {"position": "cutter", "gender-match": "women"},
    "Ellen": {"position": "cutter", "gender-match": "women"},
    "Greg": {"position": "cutter", "gender-match": "men"},
    "Henri": {"position": "cutter", "gender-match": "men"},
    "Jack": {"position": "handler", "gender-match": "men"},
    "Jake": {"position": "cutter", "gender-match": "men"},
    "Jeff": {"position": "handler", "gender-match": "men"},
    "Jeremie": {"position": "handler", "gender-match": "men"},
    "Karen": {"position": "cutter", "gender-match": "women"},
    "Kevin": {"position": "cutter", "gender-match": "men"},
    "Luke": {"position": "cutter", "gender-match": "men"},
    "Milha": {"position": "cutter", "gender-match": "women"},
    "Morgan": {"position": "handler", "gender-match": "men"},
    "Nate": {"position": "cutter", "gender-match": "men"},
    "Nicole": {"position": "cutter", "gender-match": "women"},
    "Sam": {"position": "handler", "gender-match": "men"},
    "Sonja": {"position": "cutter", "gender-match": "women"},
    "Tammy": {"position": "handler", "gender-match": "women"},
    "Victoria": {"position": "handler", "gender-match": "women"},
    "Wendy": {"position": "cutter", "gender-match": "women"},
}
